
model:
  # Clave necesaria para el script (línea 64)
  target_variable: price # <-- ¡Clave movida a este nivel!

  algorithm: GradientBoostingRegressor
  
  hyperparameters:
    n_estimators: 300
    learning_rate: 0.1
    max_depth: 3
    subsample: 0.7
  
  metadata:
    version: 4.0
    validation_metric: R2
    min_acceptable_r2: 0.90